export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const SET_VISIBILITY_MODAL = 'SET_VISIBILITY_MODAL';

export const SET_VISIBILITY_TAB = 'SET_VISIBILITY_TAB';

export const INIT_DATA_MULTISELECT = 'INIT_DATA_MULTISELECT';
export const CREATE_ELEMENT_MULTISELECT = 'CREATE_ELEMENT_MULTISELECT';
export const CHANGE_VALUE_MULTISELECT = 'CHANGE_VALUE_MULTISELECT';

export const GET_USER_AVATAR = 'GET_USER_AVATAR';
export const IMAGE_ONDRAG_ENTER = 'IMAGE_ONDRAG_ENTER';
export const IMAGE_ONDRAG_LEAVE = 'IMAGE_ONDRAG_LEAVE';
export const IMAGE_UPLOADING = 'IMAGE_UPLOADING';
export const IMAGE_UPLOADED = 'IMAGE_UPLOADED';

export const RECAPTCHA_VALIDATE = 'RECAPTCHA_VALIDATE';
export const IS_LOADING = 'IS_LOADING';

export const COMPETENCES_REPOSITORY = 'COMPETENCES_REPOSITORY';

export const  NEW_CANDIDATE = 'NEW_CANDIDATE';

export const  LOAD_CANDIDATE_DASHBOARD = 'LOAD_CANDIDATE_DASHBOARD';

export const  REMOVE_CARD_CANDIDATE = 'REMOVE_CARD_CANDIDATE';

export const OPEN_MENU = 'OPEN_MENU';

export const SETJOBTYPEID = 'SETJOBTYPEID';

export const SET_CANDIDATE_STATUS = 'SET_CANDIDATE_STATUS';

export const LOAD_VACANTS = 'LOAD_VACANTS';

export const SET_VACANT_STATUS = 'SET_VACANT_STATUS';